---
applications:
- name: member-abby
  memory: 128M
  path: ../member-app/bin/linux
  buildpacks: 
  - binary_buildpack
  command: ./member-app
  env:
    MEMBER_ID: abby
    MEMBER_NAME: "Abby Kearns"
    MEMBER_TITLE: "Executive Director"
    MEMBER_BIO: >
      With nearly twenty years in the tech world,
      Abby Kearns is a true veteran of the industry.
      Her lengthy career has spanned product marketing,
      product management and consulting across
      Fortune 500 companies and startups alike.
      As Executive Director of Cloud Foundry Foundation,
      Abby helms the ecosystem of developers, users
      and applications running on Cloud Foundry,
      and works closely with the Board to drive the
      Foundation’s vision and grow the open source project.
      Prior to Cloud Foundry Foundation,
      Abby focused on Pivotal Cloud Foundry as
      part of the Product Management team at Pivotal.
      She spent eight years at Verizon where she led
      Product Management and Product Marketing teams
      dedicated to the early days of cloud services.
      In her free time, Abby enjoys indulging in food and wine,
      and spending time with her husband and son.
