---
applications:
- name: member-swarna
  memory: 128M
  path: ../member-app/bin/linux
  buildpacks: 
  - binary_buildpack
  command: ./member-app
  env:
    MEMBER_ID: swarna
    MEMBER_NAME: "Swarna Podila"
    MEMBER_TITLE: "Senior Director, Community"
    MEMBER_BIO: >
      Swarna leads community efforts at the Foundation,
      fostering collaboration and promoting kindness.
      Prioritizing people over technology, she
      focuses on finding and amplifying the untold
      stories and lesser-known innovations of the
      people who comprise the Cloud Foundry community.
      Before joining the Foundation, Swarna worked
      as a product marketer and software engineer
      for Avi Networks, Citrix and Symantec, and
      has built and strengthened communities
      throughout her career. She loves to spend her
      non-screen time outdoors with her family.
