---
applications:
- name: member-chip
  memory: 128M
  path: ../member-app/bin/linux
  buildpacks: 
  - binary_buildpack
  command: ./member-app
  health-check-type: process
  env:
    MEMBER_ID: chip
    MEMBER_NAME: "Chip Childers"
    MEMBER_TITLE: "CTO"
    MEMBER_BIO: >
      Chip has spent 20 years in large-scale computing
      and open source software. In 2015, he became
      the co-founder of the Cloud Foundry Foundation
      as Technology Chief of Staff. He was the first
      VP of...
