---
applications:
- name: member-abby
  memory: 128M
  path: ../member-app/bin/linux
  buildpacks: 
  - binary_buildpack
  command: ./member-app
  routes:
  - members.istio.apps.internal
  env:
    MEMBER_ID: abby
    MEMBER_NAME: "Abby Kearns"
    MEMBER_TITLE: "Executive Director"
    MEMBER_BIO: >
      With nearly twenty years in the tech world,
      Abby Kearns is a true veteran of the industry.
      Her lengthy career has spanned product marketing,
      product management and consulting across
      Fortune 500...
