---
applications:
- name: member-swarna
  memory: 128M
  path: ../member-app/bin/linux
  buildpacks: 
  - binary_buildpack
  command: ./member-app
  env:
    MEMBER_ID: swarna
    MEMBER_NAME: "Swarna Podila"
    MEMBER_TITLE: "Senior Director, Community"
    MEMBER_BIO: >
      Swarna leads community efforts at the Foundation,
      fostering collaboration and promoting kindness.
      Prioritizing people over technology, she
      focuses on finding and amplifying the untold
      stories...
