#!/usr/bin/env bash

script_dir="$(cd $(dirname "$BASH_SOURCE[0]") && pwd)"


# via cf curl /v3/apps?names=cff-info-v1 | jq -r .resources[0].guid
app_guid_1="6f111577-11f6-472d-862d-eeba6773f6b0"

route_mapping_guid="f682a890-998e-40a0-937d-68e3c3c61b26"

patch_payload=$(jq \
 -c \
 -n \
 -f "$script_dir/route-mapping-clear-template.json" \
 --arg app1 "$app_guid_1")

cf curl "/v3/routes/$route_mapping_guid/destinations" \
 -X PATCH \
 -d "$patch_payload"
