#!/usr/bin/env bash

set -e
set -x

script_dir="$(cd $(dirname "$BASH_SOURCE[0]") && pwd)"

app_guid_1="$(cf curl /v3/apps?names=cff-info-v1 | jq -r .resources[0].guid)"
app_guid_2="$(cf curl /v3/apps?names=cff-info-v2 | jq -r .resources[0].guid)"

# domain of base istio ingress domain
domain_guid="$(cf curl /v3/domains?names=istio.${CF_DOMAIN} | jq -r .resources[0].guid)"

route_mapping_guid="$(cf curl /v3/routes?domain_guids=${domain_guid}\&hosts=cff-info | jq -r .resources)"

weight1="$1"
weight2="$(( 100 - weight1 ))"

patch_payload=$(jq \
 -c \
 -n \
 -f "$script_dir/route-mapping-weight-template.json" \
 --arg app1 "$app_guid_1" \
 --arg app2 "$app_guid_2" \
 --argjson weight1 "$weight1" \
 --argjson weight2 "$weight2")

cf curl "/v3/routes/$route_mapping_guid/destinations" \
 -X PATCH \
 -d "$patch_payload"
